ARG BITWARDEN_TAG
FROM ${BITWARDEN_TAG}

COPY bin/Debug/netcoreapp6.0/publish/* /vaultlibre/
COPY ./.keys/cert.cert /newLicensing.cer

RUN set -e; set -x; \
    dotnet /vaultlibre/vaultlibre.dll && \
    mv /app/Core.dll /app/Core.orig.dll && \
    mv /app/modified.dll /app/Core.dll && \
    rm -rf /vaultlibre && rm -rf /newLicensing.cer
