name: BitBetter Image

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
  schedule:
    - cron:  '0 0 * * *'
jobs:
  check_version:
    runs-on: ubuntu-latest
    name: Check Last Built Version
    outputs:
      buildimage: ${{ steps.get_version.outputs.buildimage }}
      buildversion: ${{ steps.get_version.outputs.buildversion }}
      dockerhub: ${{ steps.set_dockerhub.outputs.dockerhub }}
      dockerhubrepoapi: ${{ steps.set_dockerhub.outputs.dockerhubrepoapi }}
      dockerhubrepoidentity: ${{ steps.set_dockerhub.outputs.dockerhubrepoidentity }}
      dockerhubrepolicensegen: ${{ steps.set_dockerhub.outputs.dockerhubrepolicensegen }}
    steps:
      - uses: actions/checkout@v2
      - name: Get Latest Version
        id: get_version
        run: |
          export BW_VERSION_LATEST="$(curl --silent https://raw.githubusercontent.com/bitwarden/server/master/scripts/bitwarden.sh | grep 'COREVERSION="' | sed 's/^[^"]*"//; s/".*//')"
          export BW_VERSION_LAST_BUILT="$(cat bw_version.txt)"
          if [ $BW_VERSION_LATEST == $BW_VERSION_LAST_BUILT ]; then
            export NEED_BUILD=false
          else
            export NEED_BUILD=true
          fi
          echo "##[set-output name=buildimage;]$NEED_BUILD"
          echo "##[set-output name=buildversion;]$BW_VERSION_LATEST"
      - name: Set Dockerhub
        id: set_dockerhub
        run: |
          export DOCKERHUB=ayitaka
          export DOCKERHUBREPOAPI=bitbetter-api
          export DOCKERHUBREPOIDENTITY=bitbetter-identity
          export DOCKERHUBREPOLICENSEGEN=bitbetter-licensegen
          echo "##[set-output name=dockerhub;]$DOCKERHUB"
          echo "##[set-output name=dockerhubrepoapi;]$DOCKERHUBREPOAPI"
          echo "##[set-output name=dockerhubrepoidentity;]$DOCKERHUBREPOIDENTITY"
          echo "##[set-output name=dockerhubrepolicensegen;]$DOCKERHUBREPOLICENSEGEN"

  build_bitbetter:
    runs-on: ubuntu-latest
    name: Publish BitBetter
    needs: check_version
    if: ${{ needs.check_version.outputs.buildimage == 'true' || github.event_name == 'push' }}
    env:
      DOCKERHUB: ${{ needs.check_version.outputs.dockerhub }}
      DOCKERHUBREPOAPI: ${{ needs.check_version.outputs.dockerhubrepoapi }}
      DOCKERHUBREPOIDENTITY: ${{ needs.check_version.outputs.dockerhubrepoidentity }}
      VERSION: ${{ needs.check_version.outputs.buildversion }}
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        id: build_image
        run: |
          docker build -f ./src/bitBetter/Dockerfile --build-arg BITWARDEN_TAG=bitwarden/api:${{ needs.check_version.outputs.buildversion }} --label com.bitwarden.product="bitbetter" -t ${DOCKERHUB}/${DOCKERHUBREPOAPI} .
          docker build -f ./src/bitBetter/Dockerfile --build-arg BITWARDEN_TAG=bitwarden/identity:${{ needs.check_version.outputs.buildversion }} --label com.bitwarden.product="bitbetter" -t ${DOCKERHUB}/${DOCKERHUBREPOIDENTITY} .
      - name: Login
        run: |
          docker login -u ${{ secrets.dockerID }} -p ${{ secrets.dockerPassword }}
      - name: Deploy Latest
        run: |
          docker tag ${DOCKERHUB}/${DOCKERHUBREPOAPI} ${DOCKERHUB}/${DOCKERHUBREPOAPI}:latest
          docker tag ${DOCKERHUB}/${DOCKERHUBREPOIDENTITY} ${DOCKERHUB}/${DOCKERHUBREPOIDENTITY}:latest
          docker push ${DOCKERHUB}/${DOCKERHUBREPOAPI}:latest
          docker push ${DOCKERHUB}/${DOCKERHUBREPOIDENTITY}:latest
          echo ${DOCKERHUB}/${DOCKERHUBREPOAPI}:latest Deployed
          echo ${DOCKERHUB}/${DOCKERHUBREPOIDENTITY}:latest Deployed
      - name: Deploy Tag
        run: |
          docker tag ${DOCKERHUB}/${DOCKERHUBREPOAPI} ${DOCKERHUB}/${DOCKERHUBREPOAPI}:${VERSION}
          docker tag ${DOCKERHUB}/${DOCKERHUBREPOIDENTITY} ${DOCKERHUB}/${DOCKERHUBREPOIDENTITY}:${VERSION}
          docker push ${DOCKERHUB}/${DOCKERHUBREPOAPI}:${VERSION}
          docker push ${DOCKERHUB}/${DOCKERHUBREPOIDENTITY}:${VERSION}
          echo ${DOCKERHUB}/${DOCKERHUBREPOAPI}:${VERSION} Deployed
          echo ${DOCKERHUB}/${DOCKERHUBREPOIDENTITY}:${VERSION} Deployed
      - name: Save Version Number
        run: |
          echo ${VERSION} > bw_version.txt
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          message: "Bitwarden Version Update"
          add: "bw_version.txt"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_lic_generator:
    runs-on: ubuntu-latest
    name: Publish License Generator
    needs: [check_version, build_bitbetter]
    env:
      DOCKERHUB: ${{ needs.check_version.outputs.dockerhub }}
      DOCKERHUBREPOLICENSEGEN: ${{ needs.check_version.outputs.dockerhubrepolicensegen }}
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        id: build_image
        run: |
          docker build -f ./src/licenseGen/Dockerfile --label com.bitwarden.product="licensegen" -t ${DOCKERHUB}/${DOCKERHUBREPOLICENSEGEN} .
      - name: Login
        run: |
          docker login -u ${{ secrets.dockerID }} -p ${{ secrets.dockerPassword }}
      - name: Deploy Latest
        run: |
          docker tag ${DOCKERHUB}/${DOCKERHUBREPOLICENSEGEN} ${DOCKERHUB}/${DOCKERHUBREPOLICENSEGEN}:latest
          docker push ${DOCKERHUB}/${DOCKERHUBREPOLICENSEGEN}:latest
          echo ${DOCKERHUB}/${DOCKERHUBREPOLICENSEGEN}:latest Deployed
